import { Toaster } from "@/components/ui/sonner";
import "../globals.css";

export const metadata = {
  title: "Chic And Holland",
  description: "Generated by Next.jsChic & Holland's aim is to design and create dresses that will never go out of style - something that our discerning customers will be able to enjoy and appreciate for many years to come.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"min-h-screen bg-background antialiased"}>
        {children}

        <Toaster />
      </body>
    </html>
  );
}
