import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  fullPageContainer: {
    flex: 1,
    flexDirection: "column",
    position: "relative",
  },
  topBanner: {
    backgroundColor: "#FF5698",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
  },
  bannerText: {
    color: "black",
    fontSize: 18,
    fontWeight: "bold",
  },
  bannerTexts: {
    color: "black",
    fontSize: 25,
    fontWeight: "bold",
  },
  bannerTextPurchaseOrderNo: {
    color: "black",
    fontSize: 30,
    fontWeight: "bold",
  },
  contentContainer: {
    flex: 1,
    marginTop: 10,
    flexDirection: "column",
  },
  topContentRow: {
    flex: 1,
    flexDirection: "row",
  },
  detailsSection: {
    width: "62%",
    flexDirection: "column",
    position: "relative",
    paddingTop: 10,
    paddingBottom: 155,
    paddingRight: 8,
  },
  tableContainer: {
    border: "1px solid #000",
    borderRadius: 4,
    width: "100%",
    marginBottom: 15,
  },
  tableTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#FFD1E6",
    borderBottom: "1px solid #000",
    alignItems: "center",
  },
  tableTitle: {
    fontSize: 14,
    fontWeight: "bold",
    padding: 4,
    textAlign: "left",
    flex: 1,
  },
  orderTypeText: {
    fontSize: 14,
    fontWeight: "bold",
    padding: 4,
    color: "#0000FF",
    textAlign: "center",
  },
  tableRow: {
    flexDirection: "row",
    borderBottom: "1px solid #ccc",
  },
  mergedContainer: {
    flexDirection: "row",
    borderBottom: "1px solid #ccc",
  },
  leftMergedContainer: {
    width: "40%",
    flexDirection: "row",
  },
  rightStackedContainer: {
    width: "60%",
    flexDirection: "column",
  },
  stackedRowTop: {
    flexDirection: "row",
    borderBottom: "1px solid #ccc",
  },
  stackedRowBottom: {
    flexDirection: "row",
  },
  leftSection: {
    width: "40%",
    flexDirection: "row",
  },
  rightSection: {
    width: "60%",
    flexDirection: "row",
  },
  tableHeaderCell: {
    width: "40%",
    padding: 4,
    backgroundColor: "#FF5698",
    justifyContent: "center",
    borderRight: "1px solid #ccc",
  },
  tableDataCell: {
    width: "60%",
    padding: 4,
    backgroundColor: "#FFE6F2",
    justifyContent: "center",
    borderRight: "1px solid #ccc",
  },
  sizeHeaderCell: {
    width: "40%",
    padding: 4,
    backgroundColor: "#FF5698",
    justifyContent: "center",
    borderRight: "1px solid #ccc",
  },
  sizeDataCell: {
    width: "60%",
    padding: 4,
    backgroundColor: "#FFE6F2",
    justifyContent: "center",
    borderRight: "1px solid #ccc",
  },
  stackedHeaderCell: {
    width: "40%",
    padding: 4,
    backgroundColor: "#FF5698",
    justifyContent: "center",
    borderRight: "1px solid #ccc",
  },
  stackedDataCell: {
    width: "60%",
    padding: 4,
    backgroundColor: "#FFE6F2",
    justifyContent: "center",
    borderRight: "1px solid #ccc",
  },
  headerText: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#ffffff",
  },
  dataText: {
    fontSize: 13,
    width: "100%",
    hyphens: "none",
    wordBreak: "normal",
  },
  customizationContainer: {
    flexDirection: "column",
    marginTop: 5,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    textDecoration: "underline",
    marginBottom: 8,
    color: "#FF5698",
  },
  commentsBox: {
    border: "1px solid #ccc",
    borderRadius: 4,
    padding: 8,
    backgroundColor: "#f9f9f9",
    minHeight: 60,
  },
  commentsText: {
    fontSize: 12,
    lineHeight: 1.4,
    hyphens: "none",
    wordBreak: "normal",
  },
  extraImagesContainer: {
    position: "absolute",
    left: 0,
    right: 8,
    bottom: 0,
    flexDirection: "column",
    width: "100%",
  },
  extraImagesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-end",
  },
  additionalImage: {
    width: "48%",
    height: 145,
    objectFit: "contain",
    borderRadius: 4,
    border: "1px solid #ccc",
    marginBottom: 8,
    marginRight: "2%",
  },
  rightPanel: {
    width: "38%",
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 8,
    flexDirection: "column",
  },
  mainImageFrame: {
    height: 360,
    minHeight: 360,
    border: "1px solid #999",
    borderRadius: 4,
    padding: 6,
    justifyContent: "center",
    overflow: "hidden",
  },
  mainImagePlaceholder: {
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    padding: 12,
  },
  mainImagePlaceholderText: {
    fontSize: 11,
    color: "#666",
    textAlign: "center",
  },
  mainImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
    borderRadius: 4,
  },
  pageVariantOverlay: {
    // position: "absolute",
    top: 50,
    right: 0,
    bottom: 0,
    width: "38%",
    paddingLeft: 8,
    paddingTop: 4,
  },
  variantOverlay: {
    paddingHorizontal: 8,
    paddingTop: 7,
    paddingBottom: 8,
    borderRadius: 4,
    border: "1px solid #999",
  },
  variantOverlayTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#FF5698",
    marginBottom: 6,
    textAlign: "center",
  },
  variantGrid: {
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "stretch",
  },
  variantCard: {
    width: "24%",
    border: "1px solid #000",
    borderRadius: 4,
    paddingTop: 6,
    paddingBottom: 6,
    minHeight: 156,
    backgroundColor: "#ffffff",
    justifyContent: "space-between",
  },
  variantCardSpaced: {
    marginRight: "1.333%",
  },
  variantCardLast: {
    marginRight: 0,
  },
  variantCardTop: {
    paddingHorizontal: 5,
  },
  variantTitle: {
    fontSize: 9.5,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 4,
  },
  variantInfoGroup: {
    borderWidth: 1,
    borderColor: "#d4d4d8",
    borderRadius: 3,
  },
  variantInfoRow: {
    flexDirection: "row",
    paddingHorizontal: 2,
    paddingVertical: 1,
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  variantInfoRowBorder: {
    borderTop: "1px solid #d4d4d8",
  },
  variantInfoLabel: {
    minWidth: 28,
    fontSize: 7,
    fontWeight: "bold",
    color: "#444",
  },
  variantInfoValue: {
    flex: 1,
    fontSize: 7,
    textAlign: "left",
    marginLeft: 4,
    hyphens: "none",
    wordBreak: "normal",
  },
  colorValuesRow: {
    paddingHorizontal: 2,
    paddingVertical: 2,
    flexDirection: "column",
  },
  colorDetail: {
    fontSize: 7,
    textAlign: "left",
    hyphens: "none",
    wordBreak: "normal",
    lineHeight: 1.4,
  },
  variantBarcodeSection: {
    borderTop: "1px solid #d4d4d8",
    marginTop: 6,
    paddingTop: 5,
    // paddingHorizontal: 5,
    alignItems: "center",
  },
  variantBarcode: {
    width: 56,
    height: 56,
    alignSelf: "center",
    marginBottom: 3,
  },
  variantCodeText: {
    fontSize: 6.5,
    textAlign: "center",
    wordBreak: "break-all",
  },
});
